import { useRouter } from "next/router";
import Head from "next/head";
import Link from "next/link";
import { getEvents } from "@/components/firebase/firebase";
export default function Blog() {
  const router = useRouter();
  const { id } = router.query;
  const Events = getEvents();
  if(Events.length == 0){
    return <>Loading</>
  }
  const index = Events.findIndex((Event)=>{
    return Event.id == id;
  })
  // const Event = {
  //   name: "Solution Challenge Event",
  //   image:
  //     "https://th.bing.com/th/id/OIP.lbNwtS5QHxECLgBVO2ZLzAHaEK?pid=ImgDet&rs=1",
  //   description:
  //     "Build a solution to a local problem using Google technologies in accordance with one or more of the United Nations 17 Sustainable Development Goals.",
  //   date: "Fri, Mar 6, 7:00 AM",
  //   location: "Raj Park, New Delhi",
  //   charge: 200,
  //   sponsors: "Bing",
  //   coordinator1: "Himanshu, 8837472387",
  //   coordinator2: "Himasshu, 3438548356",
  // };
  const Event = Events[index]
  return (
    <>
      <Head>
        <title>{id}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="w-full min-h-screen bg-[#F3F4F6] flex">
          <div className="card mx-5 container shadow-lg m-auto flex  text-center min-w-[300px] p-5 rounded-md flex-col flex-wrap justify-center">
            <div className="upper flex flex-row flex-wrap justify-center">
              <div className="left max-w-sm">
                <img src={Event.image} alt="" />
              </div>
              <div className="right max-w-sm">
                <h2 className="font-bold my-3 text-xl text-[#408080]">
                  {Event.name}
                </h2>
                <p>{Event.description}</p>
              </div>
            </div>
            <div className="">
              <div className="flex justify-center w-full gap-7">
                <span className="date text-[#408080] my-3">{Event.date}</span>
                <span className="text-[#2d4747] my-3">{Event.location}</span>
              </div>
              <p className="font-bold">Coordinators</p>
              <p>{Event.coordinator1}</p>
              <p className="mb-5">{Event.coordinator2}</p>
              <Link
                href={"/register/"+id}
                className="bg-primary text-white bg-[#408080] px-4 py-2 rounded-md hover:bg-[#408080bb]"
              >
                Register
              </Link>

              <div className="text-right font-bold mt-4">
                <span className="text-right font-bold my-3">
                  {" "}
                  Sponsored By {Event.sponsors}
                </span>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
